const mongoose = require("mongoose");

const PlannedMealSchema = new mongoose.Schema(
  {
    day: {
      type: String,
      enum: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      required: true,
    },
    mealType: {
      type: String,
      enum: ["Breakfast", "Lunch", "Dinner", "Snack"],
      required: true,
    },
    food: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Food",
      required: true,
    },
    portionMultiplier: {
      type: Number,
      default: 1,
    },
    notes: String,
  },
  { _id: true }
);

const MealPlanSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // ─── Week Identification ──────────────────────────────────
    weekStartDate: {
      type: Date,
      required: [true, "Week start date is required"],
    },
    title: {
      type: String,
      default: "My Meal Plan",
      trim: true,
    },

    // ─── Planned Meals (array of day+meal slots) ──────────────
    meals: [PlannedMealSchema],

    // ─── Plan-level Targets ───────────────────────────────────
    targetCalories:  { type: Number, default: 2000 },
    targetProtein:   { type: Number, default: 120 },
    targetBudget:    { type: Number, default: 4200 }, // INR for week (600 * 7)

    // ─── Auto-generated flag ──────────────────────────────────
    isAutoGenerated: { type: Boolean, default: false },

    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

// One active plan per user per week
MealPlanSchema.index({ user: 1, weekStartDate: 1 }, { unique: false });

module.exports = mongoose.model("MealPlan", MealPlanSchema);
